[project]
name = "tracking-expence-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiosqlite>=0.22.1",
    "asyncpg>=0.31.0",
    "fastmcp>=4.0.10",
    "python-dotenv>=1.2.3",
]

[project.scripts]
tracking-expence-mcp = "tracking_expence_mcp:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
